WebApplication1/WebApplication1/Controllers/PrognosticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    

    public class PrognosticationController : Controller
    {
        BilliardEntities db = new BilliardEntities();
        // GET: Prognostication
        public ActionResult PrognosticationMain()
        {
            IEnumerable<Prognostication> prognostication = db.Prognostication;
            ViewBag.Prognostication = prognostication.OrderBy(u => u.id_competition);
            IEnumerable<Competition> competition = db.Competition;
            ViewBag.Competition = competition;
            IEnumerable<Discipline> discipline = db.Discipline;
            ViewBag.Discipline = discipline;
            return View();
        }
            public ActionResult Prognostication(int IdCompetition)
        {
            IEnumerable<Prognostication> prognostication = db.Prognostication;
            ViewBag.IdCompetition = IdCompetition;
            ViewBag.Prognostication = prognostication.OrderBy(u=>u.id_competition);
            IEnumerable<Competition> competition = db.Competition;
            ViewBag.Competition = competition;
            IEnumerable<Game> game = db.Game;
            ViewBag.Game = game;
            IEnumerable<Sportsman> sportsman = db.Sportsman;
            ViewBag.Sportsman = sportsman;
            List<int> ids = new List<int>();
            var idGame = db.Game.ToArray();
            foreach (var item in idGame)
            {
                ids.Add(item.id_game);
            }
           
            int max = 0;
            int scoreSportsman1 = 0;
            int scoreSportsman2 = 0;
            for (int i = 0; i < ids.Count; i++)
            {

                int id = ids[i];
                
                max = 0;
                Prognostication prognostications = db.Prognostication.FirstOrDefault(u => u.id_game == id);
                Game games = db.Game.FirstOrDefault(u => u.id_game == id);
                if (prognostications == null)
                {
                    if (games.sportsman_id_1 != null && games.sportsman_id_2 != null)
                    {
                        Sportsman sportsman1 = db.Sportsman.FirstOrDefault(u => u.id_sportsman == games.sportsman_id_1);
                        Sportsman sportsman2 = db.Sportsman.FirstOrDefault(u => u.id_sportsman == games.sportsman_id_2);
                        List<int> idGames = new List<int>();
                        for (int j = 0; j < ids.Count; j++)
                        {
                            int id1 = ids[j];
                            Game gameproc = db.Game.FirstOrDefault(u => u.id_game == id1);
                            if ((gameproc.sportsman_id_1 == sportsman1.id_sportsman && gameproc.sportsman_id_2 == sportsman2.id_sportsman) || (gameproc.sportsman_id_2 == sportsman1.id_sportsman && gameproc.sportsman_id_1 == sportsman2.id_sportsman))
                            {
                                if (sportsman1.id_sportsman == gameproc.sportsman_id_1)
                                {
                                    if (gameproc.score_1 > gameproc.score_2)
                                    {
                                        
                                        scoreSportsman1 = scoreSportsman1 + Convert.ToInt16(gameproc.score_1);
                                        scoreSportsman2 = scoreSportsman2 + Convert.ToInt16(gameproc.score_2);
                                        max = max + scoreSportsman1 + scoreSportsman2;

                                    }
                                    else
                                    {
                                        
                                        scoreSportsman1 = scoreSportsman1 + Convert.ToInt16(gameproc.score_1);
                                        scoreSportsman2 = scoreSportsman2 + Convert.ToInt16(gameproc.score_2);
                                        max = max + scoreSportsman1 + scoreSportsman2;
                                    }
                                }
                                else
                                {
                                    if (gameproc.score_1 > gameproc.score_2)
                                    {
                                       
                                        scoreSportsman1 = scoreSportsman1 + Convert.ToInt16(gameproc.score_2);
                                        scoreSportsman2 = scoreSportsman2 + Convert.ToInt16(gameproc.score_1);
                                        max = max + scoreSportsman1 + scoreSportsman2;
                                    }
                                    else
                                    {
                                        
                                        scoreSportsman1 = scoreSportsman1 + Convert.ToInt16(gameproc.score_2);
                                        scoreSportsman2 = scoreSportsman2 + Convert.ToInt16(gameproc.score_1);
                                        max = max + scoreSportsman1 + scoreSportsman2;

                                    }
                                }

                            }
                        }
                        double perform1=0;
                        double perform2=0;
                        if (max != 0)
                        {
                            perform1 = (scoreSportsman1 * 100) / max;
                            perform2 = (scoreSportsman2 * 100) / max;
                        }
                        
                        

                       
                        
                        db.SaveChanges();
                        double percent_sportsman_1 = 50;
                        double percent_sportsman_2 = 50;
                        double difference = 0;


                        double percen1 = (Convert.ToDouble(sportsman1.performance) * 0.3) + (Convert.ToDouble(sportsman1.point) * 0.2) + (perform1 * 0.5);
                        double percen2 = (Convert.ToDouble(sportsman2.performance) * 0.3) + (Convert.ToDouble(sportsman2.point) * 0.2) + (perform2 * 0.5);
                        if (percen1 > percen2)
                        {
                            difference = ((percen1 - percen2) / percen1) * 100;
                            difference = difference / 2;
                            percent_sportsman_1 = Math.Round((percent_sportsman_1 + difference), 2);
                            percent_sportsman_2 = Math.Round((percent_sportsman_2 - difference), 2);

                        }
                        else if (percen1 < percen2)
                        {
                            difference = ((percen2 - percen1) / percen2) * 100;
                            difference = difference / 2;
                            percent_sportsman_1 = Math.Round((percent_sportsman_1 - difference), 2);
                            percent_sportsman_2 = Math.Round((percent_sportsman_2 + difference), 2);
                        }
                        db.Prognostication.Add(new Prognostication { id_game = games.id_game, percent_sportsman_1 = percent_sportsman_1, percent_sportsman_2 = percent_sportsman_2, sportsman_id_1 = games.sportsman_id_1, sportsman_id_2 = games.sportsman_id_2,id_competition=games.id_competition });
                        db.SaveChanges();
                    }
                }
            }
            return View();
        }
      
    }

}

WebApplication1/WebApplication1/Views/Prognostication/Create.cshtml
@model WebApplication1.Prognostication

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Prognostication</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_game, "id_game", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_game", new SelectList(@ViewBag.Game, "id_game", "name_game"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_game, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.percent_sportsman_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.percent_sportsman_1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.percent_sportsman_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.percent_sportsman_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.percent_sportsman_2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.percent_sportsman_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/WebApplication1/Views/Prognostication/Prognostication.cshtml
@{
    ViewBag.Title = "Прогнози";
}
<div class="block">
    <div class="h2">
        <h2>Прогнози</h2>
    </div>

    <div class="prognostication">
        <p />
        <table class="demotable">
            <tr>
                <td>Стадія</td>
                <td>Гравець1</td>
                <td></td>
                <td></td>
                <td>Гравець2</td>

            </tr>
            @foreach (var r in ViewBag.Prognostication)
            {
                if (r.id_competition == ViewBag.IdCompetition)
                {
                <tr>
                    <td>
@foreach (var g in ViewBag.Game)
{
    if (r.id_game == g.id_game)
    {
        @g.name_game
    }
}
                    </td>
                   
                    <td>
                        @foreach (var g in ViewBag.Game)
                        {
                            if (r.id_game == g.id_game)
                            {
                                foreach (var q in ViewBag.Sportsman)
                                {
                                    if (q.id_sportsman == g.sportsman_id_1)
                                    {

                                        @q.name_sportsman

                                    }
                                }


                            }
                        }
                    </td>
                    <td>@r.percent_sportsman_1%</td>
                    <td>@r.percent_sportsman_2%</td>
                    <td>
                        @foreach (var k in ViewBag.Game)
                        {
                            if (r.id_game == k.id_game)
                            {

                                foreach (var q in ViewBag.Sportsman)
                                {
                                    if (q.id_sportsman == k.sportsman_id_2)
                                    {

                                        @q.name_sportsman

                                    }
                                }
                            }
                        }
                    </td>

                </tr>
                }
            }
        </table>
        <br />
        
    </div>
    <div>
        @Html.ActionLink("Повернутися до списку", "PrognosticationMain")
    </div>
    </div>


   <style>
    

    .h2 {
        margin-left: 5%;
    }

   

    .demotable {
        border-collapse: collapse;
        width: 90%;
        margin: auto;
        height: 10px;
        border: 1;
    }

        .demotable tr {
        }

            .demotable td,
            .demotable tr:before {
                padding: .1em .5em;
                border: 1px solid;
                color: black;
                height: 40px;
            }

            .demotable tr:before {
                display: table-cell;
                vertical-align: middle;
                color: black;
                height: 40px;
            }

    body {
        background-color: darkgreen;
    }

    .block {
        background-color: white;
    }
</style>

WebApplication1/WebApplication1/Views/Prognostication/PrognosticationMain.cshtml
@{
    ViewBag.Title = "Прогнози";
}
<div class="block">
    <div class="h2">
        <h2>Прогнози</h2>
    </div>

    <div class="prognostication">
        <p />
       
        <table class="demotable" width=90% height=10px border=1 valign=MIDDLE>
            <tr>
                <td>Назва змагань</td>
                <td>Дисципліна</td>
                <td>Країна</td>
                <td>Місто</td>
            </tr>
             @foreach (var item in ViewBag.Competition)
                {
                <tr>  
                    <td>@Html.ActionLink((string)item.name_competition, "Prognostication", new { IdCompetition = @item.id_competition })</td>
                    <td>
                        @foreach (var q in ViewBag.Discipline)
                        {
                            if (item.id_discipline == q.id_discipline)
                            {
                                @q.name_discipline
                            }
                        }
                    </td>
                    <td>@item.country_competition</td>
                    <td>@item.city_competition</td>

                    
                    
                </tr>
                }     
        </table>
        <br />
    </div>
</div>

<style>
 

    .h2 {
        margin-left: 5%;
    }


    .demotable {
        border-collapse: collapse;
        counter-reset: schetchik;
        margin: auto;
    }

        .demotable tbody tr:nth-child(n+2) {
            counter-increment: schetchik;
        }

        .demotable td,
        .demotable tbody tr:before {
            padding: .1em .5em;
            border: 1px solid;
        }

        .demotable tbody tr:before {
            display: table-cell;
            vertical-align: middle;
            height: 35px;
        }

        .demotable tbody tr:before,
        .demotable b:after {
            content: counter(schetchik);
            color: black;
            height: 35px;
        }

        .demotable tbody tr:nth-child(-n+1):before {
            content: "";
        }

    body {
        background-color: darkgreen;
    }

    .block {
        background-color: white;
    }
</style>