WebApplication1/WebApplication1/Controllers/CompetitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Optimization;
using System.Web.UI;
using WebApplication1.Models;


namespace WebApplication1.Controllers
{
    public class CompetitionController : Controller
    {
        BilliardEntities db = new BilliardEntities();
        // GET: Competition
        int Size = 0;
        
        public ActionResult Grid(int IdCompetition)
        {

            IEnumerable<Sportsman> sportsman = db.Sportsman;
            ViewBag.Sportsman = sportsman;
            ViewBag.IdCompetition = IdCompetition;
            return View();
        }

        public ActionResult Regulations(int IdCompetition)
        {
            Bundle jqmobile = new ScriptBundle("~/bundle/jquerymobile")
               .Include("~/Scripts/jquery-{version}.js",
                   "~/Scripts/jquery.mobile-{version}.js");

            Bundle jqmobileCSS =
                new StyleBundle("~/bundle/jquerymobileCSS")
                    .Include("~/Content/jquery.mobile-{version}.css");

            IEnumerable<Competition> competition = db.Competition;
            ViewBag.competition = competition;
            IEnumerable<Discipline> discipline = db.Discipline;
            ViewBag.Discipline = discipline;
            ViewBag.IdCompetition = IdCompetition;
            return View();
        }
        public ActionResult Games(int IdCompetition)
        {
            Bundle jqmobile = new ScriptBundle("~/bundle/jquerymobile")
               .Include("~/Scripts/jquery-{version}.js",
                   "~/Scripts/jquery.mobile-{version}.js");

            Bundle jqmobileCSS =
                new StyleBundle("~/bundle/jquerymobileCSS")
                    .Include("~/Content/jquery.mobile-{version}.css");

            IEnumerable<Competition> competition = db.Competition;
            ViewBag.competition = competition;
            IEnumerable<Discipline> discipline = db.Discipline;
            ViewBag.Discipline = discipline;
            ViewBag.IdCompetition = IdCompetition;
            return View();
        }

        public ActionResult ResultSportsman(int IdCompetition)
        {
            Bundle jqmobile = new ScriptBundle("~/bundle/jquerymobile")
               .Include("~/Scripts/jquery-{version}.js",
                   "~/Scripts/jquery.mobile-{version}.js");

            Bundle jqmobileCSS =
                new StyleBundle("~/bundle/jquerymobileCSS")
                    .Include("~/Content/jquery.mobile-{version}.css");
            IEnumerable<Competition> competition = db.Competition;
            ViewBag.Competition = competition;
            IEnumerable<Sportsman> sportsman = db.Sportsman;
            ViewBag.Sportsman = sportsman;
            IEnumerable<Ranks> ranks = db.Ranks;
            ViewBag.Ranks = ranks;
            IEnumerable<Competition_sportsman> competition_Sportsman = db.Competition_sportsman;
            ViewBag.CompetitionSportsman = competition_Sportsman.OrderByDescending(u=>u.points);
            IEnumerable<Game> game = db.Game;
            ViewBag.Game = game;
            ViewBag.IdCompetition = IdCompetition;
            return View();
        }

        public ActionResult Competitions()
        {
            
            IEnumerable<Competition> competition = db.Competition;
            ViewBag.competition = competition.OrderBy(u=>u.competiton_status);
            IEnumerable<Discipline> discipline = db.Discipline;
            ViewBag.Discipline = discipline;

            return View();
        }
        
        public ActionResult Create()
        {
            IEnumerable<Competition> competition = db.Competition;
            ViewBag.competition = competition;
            IEnumerable<Discipline> discipline = db.Discipline;
            ViewBag.Discipline = discipline;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create(Competition add)
        {
            
            IEnumerable<Discipline> discipline = db.Discipline;
            ViewBag.Discipline = discipline;
            if (ModelState.IsValid)
            {
                Competition competition = null;
                competition = db.Competition.FirstOrDefault(u => u.name_competition == add.name_competition);
                IEnumerable<Competition> competitions = db.Competition;
                ViewBag.Competition = competitions;



                if (competition == null)
                {
                    db.Competition.Add(new Competition { id_competition = add.id_competition, name_competition = add.name_competition, date_start=add.date_start,date_end=add.date_end,id_discipline=add.id_discipline,country_competition=add.country_competition,city_competition=add.city_competition, competiton_status=add.competiton_status, regulation=add.regulation  });
                    db.SaveChanges();

                    ModelState.AddModelError("", "Змагання успішно додано");
                }
                else
                    ModelState.AddModelError("", "Змагання з такою назвою вже існує");
            }

            return View();
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            
            IEnumerable<Competition> competition = db.Competition;
            ViewBag.Competition = competition;
            IEnumerable<Sportsman> sportsman = db.Sportsman;
            ViewBag.Sportsman = sportsman;
            Competition competitions = db.Competition.FirstOrDefault(u => u.id_competition == id);
            IEnumerable<Discipline> discipline = db.Discipline;
            ViewBag.Discipline = discipline;
            if (competitions == null)
                return View("Error");

            return View(competitions);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Competition edit)
        {
            IEnumerable<Competition> competition = db.Competition;
            ViewBag.Competition = competition;
            IEnumerable<Discipline> discipline = db.Discipline;
            ViewBag.Discipline = discipline;
            Competition competitions = db.Competition.FirstOrDefault(u => u.id_competition == id);
            if (competitions != null)
            {
                if (ModelState.IsValid)
                {
                    
                    competitions.name_competition = edit.name_competition;
                    competitions.date_start = edit.date_start;
                    competitions.date_end = edit.date_end;
                    competitions.id_discipline = edit.id_discipline;
                    competitions.country_competition = edit.country_competition;
                    competitions.city_competition = edit.city_competition;
                    competitions.regulation = edit.regulation;
                    
                    db.SaveChanges();
                    ModelState.AddModelError("", "Зміни збереженно");
                }
            }
            else
                ModelState.AddModelError("", "Змагання не знайдено");

            return View(competitions);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Competition competition = db.Competition.FirstOrDefault(u => u.id_competition == id);

            if (competition == null)
                return View("Error");

            return View(competition);
        }


        [HttpPost]
        public ActionResult Delete(int? id)
        {
            Competition competition = db.Competition.FirstOrDefault(u => u.id_competition == id);

            if (competition != null)
            {
                db.Competition.Remove(competition);
                db.SaveChanges();

                return RedirectToAction("Competitions");
            }
            else
                ModelState.AddModelError("", "Змагання не знайдено");

            return View("");
        }

        public ActionResult CompetitionSportsman(int IdCompetition)
        {
            IEnumerable<Competition> competition = db.Competition;
            ViewBag.Competition = competition;
            
            IEnumerable<Sportsman> sportsman = db.Sportsman;
            ViewBag.Sportsman = sportsman;
            IEnumerable<Ranks> ranks = db.Ranks;
            ViewBag.Ranks = ranks;
            IEnumerable<Competition_sportsman> competition_Sportsman = db.Competition_sportsman;
            ViewBag.CompetitionSportsman = competition_Sportsman;
            Competition_sportsman competition_Sportsmans= db.Competition_sportsman.Where(u => u.id_competition == IdCompetition).FirstOrDefault(u => u.toss!=null);
            ViewBag.Competition_sportsmans = competition_Sportsmans;
            IEnumerable<Game> game = db.Game;
            ViewBag.Game = game;
            ViewBag.IdCompetition = IdCompetition;
            

            return View(IdCompetition);
        }
        public ActionResult AddSportsman(int IdCompetition)
        {
            IEnumerable<Competition> competition = db.Competition;
            ViewBag.competition = competition;
            IEnumerable<Sportsman> sportsman = db.Sportsman;
            ViewBag.Sportsman = sportsman;
            IEnumerable<Competition_sportsman> competition_Sportsman = db.Competition_sportsman;
            ViewBag.Competition_sportsman = competition_Sportsman;
            ViewBag.IdCompetition = IdCompetition;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddSportsman(Competition_sportsman add,int IdCompetition,Sportsman edit)
        {
            
            IEnumerable<Competition> competition = db.Competition;
            ViewBag.competition = competition;
            IEnumerable<Sportsman> sportsman = db.Sportsman;
            ViewBag.Sportsman = sportsman;
            ViewBag.IdCompetition = IdCompetition;

WebApplication1/WebApplication1/Controllers/RegulationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class RegulationsController : Controller
    {
        // GET: Regulations
        public ActionResult Regulations()

        {

            return View();
        }
        public ActionResult PyramidRules()

        {

            return View();
        }
        public ActionResult StraightCannon ()

        {

            return View();
        }
        public ActionResult SimpleChips()

        {

            return View();
        }
        public ActionResult FiveChips()

        {

            return View();
        }
        public ActionResult SingleBreastedCannon()

        {

            return View();
        }
        public ActionResult ThreeBreastedCannon()

        {

            return View();
        }
        public ActionResult FreePyramid()

        {

            return View();
        }
        public ActionResult CombinedPyramid()

        {

            return View();
        }
        public ActionResult DynamicPyramid()

        {

            return View();
        }
        public ActionResult ClassicPyramidFiftyOne()

        {

            return View();
        }
        public ActionResult ClassicPyramidEight()

        {

            return View();
        }
        public ActionResult ClassicPyramidSeventyOne()

        {

            return View();
        }
        public ActionResult PyramidTeamCompetitions()

        {

            return View();
        }
        public ActionResult GeneralPoolRules()

        {

            return View();
        }
        public ActionResult PoolOfEight()

        {

            return View();
        }
        public ActionResult PoolOfNine()

        {

            return View();
        }
        public ActionResult PoolfFourteenPlusOne()

        {

            return View();
        }
        public ActionResult Snooker()

        {

            return View();
        }
    }
}

WebApplication1/WebApplication1/Views/Game/Create.cshtml
@model WebApplication1.Game

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Game</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name_game, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name_game, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name_game, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.game_status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.game_status)
                    @Html.ValidationMessageFor(model => model.game_status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.sportsman_id_1, "sportsman_id_1", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.DropDownList("sportsman_id_1", new SelectList(@ViewBag.Sportsman, "id_sportsman", "name_sportsman"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.sportsman_id_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sportsman_id_2, "sportsman_id_2", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("sportsman_id_2", new SelectList(@ViewBag.Sportsman, "id_sportsman", "name_sportsman"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.sportsman_id_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.score_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.score_1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.score_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.score_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.score_2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.score_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_competition, "id_competition", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_competition", new SelectList(@ViewBag.Competition, "id_competition", "name_competition"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_competition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/WebApplication1/Views/Game/Delete.cshtml
@model WebApplication1.Game

@{
    ViewBag.Title = "Видалення гри";
}



<h3>Ви дійсно хочете видалити гру?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Назва гри")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name_game)
        </dd>

        <dt>
            @Html.DisplayName("Статус гри")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.game_status)
        </dd>

  

        <dt>
            @Html.DisplayName("Рахунок першого спортсмена")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.score_1)
        </dd>

        <dt>
            @Html.DisplayName("Рахунок другого спортсмена")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.score_2)
        </dd>

        <dt>
            @Html.DisplayName("Назва Змагань")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_competition)
        </dd>

        <dt>
            @Html.DisplayName("Ім'я першого спорсмена")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sportsman_id_1)
        </dd>

        <dt>
            @Html.DisplayName("Ім'я другого спорсмена")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sportsman_id_2)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Видалити" class="btn btn-default" /> |
            @Html.ActionLink("Повернутися назад", "Game")
        </div>
    }
</div>

WebApplication1/WebApplication1/Views/Game/Edit.cshtml
@model WebApplication1.Game

@{
    ViewBag.Title = "Edit";
}

<h2>Виставлення рахунку</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_game)

        <div class="form-group">
            @Html.LabelFor(model => model.name_game,"Стадія гри:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @foreach (var g in ViewBag.Game)
                {
                    if (g.id_game == ViewBag.Id)
                    {
                        @g.name_game

                    }
                }
               
            </div>
        </div>

     

        <div class="form-group">
            @Html.LabelFor(model => model.sportsman_id_1, "Перший спортсмен", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @foreach (var g in ViewBag.Game)
                {
                    foreach (var r in ViewBag.Sportsman)
                    {
                        if (g.id_game == ViewBag.Id)
                        {
                            if (g.sportsman_id_1 == r.id_sportsman)
                            {
                        @r.name_sportsman
                            }
                        }
                    }
                }
                


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sportsman_id_2, "Другий спортсмен", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @foreach (var g in ViewBag.Game)
                {
                    foreach (var r in ViewBag.Sportsman)
                    {
                        if (g.id_game == ViewBag.Id)
                        {
                            if (g.sportsman_id_2 == r.id_sportsman)
                            {
                                @r.name_sportsman
                            }
                        }
                    }
                }
               


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.score_1, "Рахунок 1", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.score_1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.score_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.score_2, "Рахунок 2", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.score_2,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.score_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_competition, "Змагання", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @foreach(var g in ViewBag.Competition)
               {
                       if (g.id_competition == ViewBag.IdCompetition)
                       {
                          @g.name_competition
                                                   
                   }
               }


            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зберегти" class="btn btn-default" />
            </div>
        </div>
    </div>
}


    <li><a href="/Game/Game/@ViewBag.IdCompetition">Ігри</a></li>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/WebApplication1/Views/Game/Game.cshtml
@{
    ViewBag.Title = "Ігри";
}
<div class="block">
    <div class="h2">
        <h2>Ігри</h2>
    </div>


    <div class="Game">
        <p />

 
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Регламент", "Regulations", "Competition", new { IdCompetition = @ViewBag.IdCompetition }, null)</li>
                            <li>@Html.ActionLink("Спортсмени", "CompetitionSportsman", "Competition", new { IdCompetition = @ViewBag.IdCompetition }, null)</li>

                            <li>Ігри</li>
                            <li>@Html.ActionLink("Результат", "ResultSportsman", "Competition", new { IdCompetition = @ViewBag.IdCompetition }, null)</li>
                        </ul>
                    </div>
                    
                    <table class="demotable">
                        <tr>

                            <td>Стадія турніру</td>

                            <td>Спортсмен 1</td>
                            <td>Рахунок</td>
                            <td>Спортсмен 2</td>


                        </tr>
                        @foreach (var r in ViewBag.Game)
            {

                if (r.id_competition == ViewBag.IdCompetition)
                {
                                <tr>

                                    <td>@r.name_game фіналу</td>


                                    <td>
                                        @foreach (var g in ViewBag.Sportsman)
                                        {
                                            if (r.sportsman_id_1 == g.id_sportsman)
                                            {
                                                @g.name_sportsman
                                            }
                                        }
                                    </td>
                                    <td align="center">@r.score_1 : @r.score_2 </td>
                                    <td>
                                        @foreach (var q in ViewBag.Sportsman)
                                        {
                                            if (r.sportsman_id_2 == q.id_sportsman)
                                            {
                                                @q.name_sportsman
                                            }
                                        }
                                    </td>

                                  @if (User.IsInRole("admin"))
                                  {
                                    foreach (var q in ViewBag.Competition)
                                    {
                                        if (r.id_competition == q.id_competition)
                                        {
                                            if (q.competiton_status != true)
                                            {
                                    <td>@Html.ActionLink("Виставити рахунок", "Edit", "Game", new { id = @r.id_game, IdCompetition = @ViewBag.IdCompetition }, null)</td>
                                                }
                                            }
                                        }
                                    }
                                </tr>
                            }
                        }
                    </table>
                    <br />

                </div>
            </div>
      


            <style>
                .a {
                    margin-left: 5%;
                }

                .h2 {
                    margin-left: 5%;
                }

                .navbar-collapse {
                    margin-left: 5%;
                }

                .demotable {
                    border-collapse: collapse;
                    width: 90%;
                    margin: auto;
                    height: 10px;
                    border: 1;
                }

                    .demotable tr {
                    }

                        .demotable td,
                        .demotable tr:before {
                            padding: .1em .5em;
                            border: 1px solid;
                            color: black;
                            height: 40px;
                        }

                        .demotable tr:before {
                            display: table-cell;
                            vertical-align: middle;
                            color: black;
                            height: 40px;
                        }

                body {
                    background-color: darkgreen;
                }

                .block {
                    background-color: white;
                }
            </style>